### PR TITLE
Rename along vue style guide

### PR DESCRIPTION
**Pull request by potato4d**
At the Vue 2.4 update, Vue's style guide was released in their community.
But, `nuxt-community/starter-template` did not follow it.

So, I renamed files alog style guide.

https://vuejs.org/v2/style-guide/#Multi-word-component-names-essential

### CODE REVIEW

**Comment by atinux** [comment]
Done here: https://github.com/nuxt-community/starter-template/commit/625118997e0475a2513562ebde9086c259e5c108

Thanks @potato4d

**Comment by potato4d** [comment]
@Atinux 
Thank you merge 🤗 
But, I wanted merge commit or squash merge if possible :cry:

**Comment by atinux** [comment]
Yes I am sorry but it was a conflict into the PR and sadly I'm not a git expert :(

**Comment by potato4d** [comment]
@Atinux
Oh, It's OK.
If you have something similar again please contact me :)

**Comment by atinux** [comment]
I believe you can do these changes into https://github.com/nuxt-community/create-nuxt-app directly, it's the tool we aim to all use in the future :)

**Pull request closed without merging**
